import type { Destination } from './types';

export const destinations: Destination[] = [
  {city:'Jeddah',country:'Saudi Arabia',iata:'JED',currency:'SAR',region:'Saudi Arabia',hotelNight:260,dailyFood:95,dailyLocal:55,dailyActivities:75},
  {city:'Riyadh',country:'Saudi Arabia',iata:'RUH',currency:'SAR',region:'Saudi Arabia',hotelNight:300,dailyFood:105,dailyLocal:65,dailyActivities:90},
  {city:'Dammam',country:'Saudi Arabia',iata:'DMM',currency:'SAR',region:'Saudi Arabia',hotelNight:250,dailyFood:90,dailyLocal:55,dailyActivities:70},
  {city:'Madinah',country:'Saudi Arabia',iata:'MED',currency:'SAR',region:'Saudi Arabia',hotelNight:245,dailyFood:80,dailyLocal:45,dailyActivities:45},
  {city:'Abha',country:'Saudi Arabia',iata:'AHB',currency:'SAR',region:'Saudi Arabia',hotelNight:220,dailyFood:75,dailyLocal:45,dailyActivities:70},
  {city:'Taif',country:'Saudi Arabia',iata:'TIF',currency:'SAR',region:'Saudi Arabia',hotelNight:210,dailyFood:75,dailyLocal:40,dailyActivities:65},
  {city:'AlUla',country:'Saudi Arabia',iata:'ULH',currency:'SAR',region:'Saudi Arabia',hotelNight:420,dailyFood:110,dailyLocal:80,dailyActivities:170},
  {city:'Tabuk',country:'Saudi Arabia',iata:'TUU',currency:'SAR',region:'Saudi Arabia',hotelNight:210,dailyFood:75,dailyLocal:45,dailyActivities:60},
  {city:'Jazan',country:'Saudi Arabia',iata:'GIZ',currency:'SAR',region:'Saudi Arabia',hotelNight:190,dailyFood:70,dailyLocal:40,dailyActivities:65},
  {city:'Yanbu',country:'Saudi Arabia',iata:'YNB',currency:'SAR',region:'Saudi Arabia',hotelNight:210,dailyFood:80,dailyLocal:45,dailyActivities:75},
  {city:'Al Baha',country:'Saudi Arabia',iata:'ABT',currency:'SAR',region:'Saudi Arabia',hotelNight:195,dailyFood:70,dailyLocal:42,dailyActivities:65},
  {city:'Hail',country:'Saudi Arabia',iata:'HAS',currency:'SAR',region:'Saudi Arabia',hotelNight:185,dailyFood:70,dailyLocal:38,dailyActivities:55},
  {city:'Qassim',country:'Saudi Arabia',iata:'ELQ',currency:'SAR',region:'Saudi Arabia',hotelNight:190,dailyFood:75,dailyLocal:42,dailyActivities:55},
  {city:'Najran',country:'Saudi Arabia',iata:'EAM',currency:'SAR',region:'Saudi Arabia',hotelNight:180,dailyFood:70,dailyLocal:38,dailyActivities:50},
  {city:'Al Ahsa',country:'Saudi Arabia',iata:'HOF',currency:'SAR',region:'Saudi Arabia',hotelNight:195,dailyFood:75,dailyLocal:42,dailyActivities:60},
  {city:'Sakaka',country:'Saudi Arabia',iata:'AJF',currency:'SAR',region:'Saudi Arabia',hotelNight:180,dailyFood:68,dailyLocal:38,dailyActivities:50},
  {city:'Arar',country:'Saudi Arabia',iata:'RAE',currency:'SAR',region:'Saudi Arabia',hotelNight:175,dailyFood:68,dailyLocal:36,dailyActivities:48},
  {city:'Makkah',country:'Saudi Arabia',iata:'JED',currency:'SAR',region:'Saudi Arabia',hotelNight:280,dailyFood:85,dailyLocal:55,dailyActivities:45},
  {city:'Khobar',country:'Saudi Arabia',iata:'DMM',currency:'SAR',region:'Saudi Arabia',hotelNight:260,dailyFood:95,dailyLocal:55,dailyActivities:75},
  {city:'Jubail',country:'Saudi Arabia',iata:'DMM',currency:'SAR',region:'Saudi Arabia',hotelNight:240,dailyFood:90,dailyLocal:52,dailyActivities:60},
  {city:'Dubai',country:'United Arab Emirates',iata:'DXB',currency:'AED',region:'GCC',hotelNight:390,dailyFood:150,dailyLocal:85,dailyActivities:170},
  {city:'Abu Dhabi',country:'United Arab Emirates',iata:'AUH',currency:'AED',region:'GCC',hotelNight:360,dailyFood:145,dailyLocal:80,dailyActivities:155},
  {city:'Sharjah',country:'United Arab Emirates',iata:'SHJ',currency:'AED',region:'GCC',hotelNight:275,dailyFood:115,dailyLocal:62,dailyActivities:100},
  {city:'Ras Al Khaimah',country:'United Arab Emirates',iata:'RKT',currency:'AED',region:'GCC',hotelNight:290,dailyFood:120,dailyLocal:65,dailyActivities:120},
  {city:'Al Ain',country:'United Arab Emirates',iata:'AAN',currency:'AED',region:'GCC',hotelNight:250,dailyFood:110,dailyLocal:60,dailyActivities:95},
  {city:'Fujairah',country:'United Arab Emirates',iata:'FJR',currency:'AED',region:'GCC',hotelNight:275,dailyFood:115,dailyLocal:65,dailyActivities:110},
  {city:'Doha',country:'Qatar',iata:'DOH',currency:'QAR',region:'GCC',hotelNight:340,dailyFood:135,dailyLocal:70,dailyActivities:130},
  {city:'Kuwait City',country:'Kuwait',iata:'KWI',currency:'KWD',region:'GCC',hotelNight:32,dailyFood:13,dailyLocal:7,dailyActivities:11},
  {city:'Manama',country:'Bahrain',iata:'BAH',currency:'BHD',region:'GCC',hotelNight:35,dailyFood:14,dailyLocal:7,dailyActivities:12},
  {city:'Muharraq',country:'Bahrain',iata:'BAH',currency:'BHD',region:'GCC',hotelNight:32,dailyFood:13,dailyLocal:7,dailyActivities:10},
  {city:'Muscat',country:'Oman',iata:'MCT',currency:'OMR',region:'GCC',hotelNight:34,dailyFood:12,dailyLocal:7,dailyActivities:13},
  {city:'Salalah',country:'Oman',iata:'SLL',currency:'OMR',region:'GCC',hotelNight:30,dailyFood:11,dailyLocal:7,dailyActivities:14},
  {city:'Sohar',country:'Oman',iata:'OHS',currency:'OMR',region:'GCC',hotelNight:28,dailyFood:10,dailyLocal:6,dailyActivities:10},
  {city:'Duqm',country:'Oman',iata:'DQM',currency:'OMR',region:'GCC',hotelNight:29,dailyFood:10,dailyLocal:6,dailyActivities:9},
  {city:'Cairo',country:'Egypt',iata:'CAI',currency:'EGP',region:'Arab World',hotelNight:2400,dailyFood:850,dailyLocal:420,dailyActivities:650},
  {city:'Alexandria',country:'Egypt',iata:'HBE',currency:'EGP',region:'Arab World',hotelNight:2100,dailyFood:780,dailyLocal:380,dailyActivities:600},
  {city:'Amman',country:'Jordan',iata:'AMM',currency:'JOD',region:'Arab World',hotelNight:42,dailyFood:18,dailyLocal:10,dailyActivities:18},
  {city:'Aqaba',country:'Jordan',iata:'AQJ',currency:'JOD',region:'Arab World',hotelNight:48,dailyFood:19,dailyLocal:9,dailyActivities:24},
  {city:'Beirut',country:'Lebanon',iata:'BEY',currency:'USD',region:'Arab World',hotelNight:72,dailyFood:34,dailyLocal:16,dailyActivities:26},
  {city:'Casablanca',country:'Morocco',iata:'CMN',currency:'MAD',region:'Arab World',hotelNight:620,dailyFood:220,dailyLocal:95,dailyActivities:170},
  {city:'Marrakech',country:'Morocco',iata:'RAK',currency:'MAD',region:'Arab World',hotelNight:690,dailyFood:235,dailyLocal:105,dailyActivities:210},
  {city:'Tunis',country:'Tunisia',iata:'TUN',currency:'TND',region:'Arab World',hotelNight:150,dailyFood:55,dailyLocal:25,dailyActivities:45},
  {city:'Algiers',country:'Algeria',iata:'ALG',currency:'DZD',region:'Arab World',hotelNight:7800,dailyFood:2600,dailyLocal:1200,dailyActivities:1900},
  {city:'Oran',country:'Algeria',iata:'ORN',currency:'DZD',region:'Arab World',hotelNight:6900,dailyFood:2400,dailyLocal:1050,dailyActivities:1750},
  {city:'Baghdad',country:'Iraq',iata:'BGW',currency:'IQD',region:'Arab World',hotelNight:68000,dailyFood:26000,dailyLocal:13000,dailyActivities:18000},
  {city:'Erbil',country:'Iraq',iata:'EBL',currency:'IQD',region:'Arab World',hotelNight:74000,dailyFood:29000,dailyLocal:14000,dailyActivities:21000},
  {city:'Ramallah / West Bank',country:'Palestine',iata:'JRS',currency:'ILS',region:'Arab World',hotelNight:240,dailyFood:105,dailyLocal:50,dailyActivities:80},
  {city:'Tripoli',country:'Libya',iata:'MJI',currency:'LYD',region:'Arab World',hotelNight:290,dailyFood:90,dailyLocal:45,dailyActivities:60},
  {city:'Damascus',country:'Syria',iata:'DAM',currency:'USD',region:'Arab World',hotelNight:48,dailyFood:20,dailyLocal:10,dailyActivities:14},
  {city:'Aden',country:'Yemen',iata:'ADE',currency:'USD',region:'Arab World',hotelNight:42,dailyFood:18,dailyLocal:9,dailyActivities:12},
  {city:'Port Sudan',country:'Sudan',iata:'PZU',currency:'USD',region:'Arab World',hotelNight:46,dailyFood:19,dailyLocal:10,dailyActivities:13},
  {city:'Djibouti',country:'Djibouti',iata:'JIB',currency:'DJF',region:'Arab World',hotelNight:11000,dailyFood:4600,dailyLocal:2200,dailyActivities:3000},
  {city:'Mogadishu',country:'Somalia',iata:'MGQ',currency:'USD',region:'Arab World',hotelNight:65,dailyFood:28,dailyLocal:15,dailyActivities:16},
  {city:'Nouakchott',country:'Mauritania',iata:'NKC',currency:'MRU',region:'Arab World',hotelNight:1700,dailyFood:720,dailyLocal:320,dailyActivities:500},
  {city:'Moroni',country:'Comoros',iata:'HAH',currency:'KMF',region:'Arab World',hotelNight:24500,dailyFood:9600,dailyLocal:4200,dailyActivities:7000}
];

export const placeKey = (d: Pick<Destination,'country'|'city'>) => `${d.country}|${d.city}`;
export const uniqueDestinations = Array.from(new Map(destinations.map(d => [placeKey(d), d])).values());
export const countries = Array.from(new Set(uniqueDestinations.map(d=>d.country)));
export const gccCurrencies = ['SAR','AED','KWD','BHD','QAR','OMR'] as const;
