'use client';
import {useMemo,useState} from 'react';
import {gccCurrencies,placeKey,uniqueDestinations} from '@/lib/destinations';
import type {SearchInput,TripResult,CostLine} from '@/lib/types';
import s from './FinalPlanner.module.css';

type Lang='ar'|'en';
const fxFallback:Record<string,number>={SAR:1,AED:1.021,QAR:1.03,KWD:12.2,BHD:9.95,OMR:9.75};
const ar:Record<string,string>={'Saudi Arabia':'السعودية','United Arab Emirates':'الإمارات','Qatar':'قطر','Kuwait':'الكويت','Bahrain':'البحرين','Oman':'عُمان','Jeddah':'جدة','Riyadh':'الرياض','Dammam':'الدمام','Madinah':'المدينة','Makkah':'مكة','Abha':'أبها','Taif':'الطائف','AlUla':'العلا','Tabuk':'تبوك','Jazan':'جازان','Dubai':'دبي','Abu Dhabi':'أبوظبي','Sharjah':'الشارقة','Doha':'الدوحة','Kuwait City':'الكويت','Manama':'المنامة','Muscat':'مسقط','Salalah':'صلالة','Cairo':'القاهرة','Alexandria':'الإسكندرية','Amman':'عمّان','Aqaba':'العقبة','Beirut':'بيروت','Casablanca':'الدار البيضاء','Marrakech':'مراكش'};
const labels={ar:{title:'ميزانيتك أولًا.',sub:'ميزان يبحث عن أوفر رحلة ويشرح لك من أين جاء كل ريال في الحسبة.',budget:'عندي ميزانية',dest:'أعرف وجهتي',origin:'مدينة الانطلاق',destination:'الوجهة',money:'الميزانية',days:'مدة الرحلة بالأيام',adults:'البالغون',children:'الأطفال',style:'نمط الصرف',when:'وقت السفر',any:'أي وقت — ابحث عن الأرخص',specific:'تاريخ محدد',date:'تاريخ المغادرة',window:'فترة البحث',emergency:'احتياطي الطوارئ',essentials:'الضروريات اليومية',hotel:'السكن',food:'الأكل',local:'التنقل',activities:'الأنشطة',search:'جيب أوفر الرحلات',loading:'جاري فحص التواريخ والحسبة…',results:'النتائج مرتبة من الأرخص',core:'تكلفة الرحلة',safe:'الميزانية الآمنة المقترحة',left:'المتبقي',party:'المسافرون',stay:'الإقامة',details:'كيف حسبنا هذه النتيجة؟',method:'كل بند يوضح نوع السعر والمعادلة والأساس.',live:'مباشر',reference:'مرجعي',allowance:'ميزانية تقديرية',empty:'ما لقينا نتائج بهذه المدخلات.',error:'تعذر حساب الرحلة الآن.'},en:{title:'Budget first.',sub:'MIZAN finds the cheapest trips and shows exactly where every number comes from.',budget:'I have a budget',dest:'I know my destination',origin:'Origin city',destination:'Destination',money:'Total budget',days:'Trip days',adults:'Adults',children:'Children',style:'Spending style',when:'Travel dates',any:'Anytime — find cheapest',specific:'Specific date',date:'Departure',window:'Search window',emergency:'Emergency reserve',essentials:'Daily essentials',hotel:'Stay',food:'Food',local:'Local transport',activities:'Experiences',search:'Find cheapest trips',loading:'Scanning dates and calculating…',results:'Results sorted cheapest first',core:'Core trip cost',safe:'Recommended safe budget',left:'Remaining',party:'Travelers',stay:'Stay',details:'How was this calculated?',method:'Every line shows its price type, formula and basis.',live:'Live',reference:'Reference',allowance:'Estimated allowance',empty:'No results for these inputs.',error:'Could not calculate this trip.'}};
const lineNames:Record<string,{ar:string,en:string}>={flight:{ar:'الذهاب والعودة',en:'Travel fare'},hotel:{ar:'السكن',en:'Accommodation'},food:{ar:'الأكل',en:'Food'},local:{ar:'التنقل المحلي',en:'Local transport'},activities:{ar:'الأنشطة والتجارب',en:'Experiences'},essentials:{ar:'الضروريات',en:'Essentials'},emergency:{ar:'احتياطي الطوارئ',en:'Emergency reserve'}};
const explainAr:Record<string,string>={flight:'إذا توفر مزود مباشر نستخدم سعره؛ وإلا يظهر بوضوح كسعر مرجعي.',hotel:'عدد الليالي × عدد الغرف × السعر المرجعي لليلة، مع نمط الصرف.',food:'ميزانية يومية × عدد الأيام × البالغين، والأطفال محسوبون بنسبة 65%.',local:'ميزانية تنقل يومية عادية. السائق الخاص وتأجير السيارة إضافات منفصلة.',activities:'ميزانية يومية للأنشطة وليست ادعاءً بحجز فعالية محددة بهذا السعر.',essentials:'مخصص للمياه والاحتياجات اليومية الصغيرة. الإنترنت والتأمين والتأشيرة إضافات منفصلة.',emergency:'نسبة أمان اختيارية فوق تكلفة الرحلة وليست خدمة مشتراة.'};
const todayPlus=(n:number)=>{const d=new Date();d.setDate(d.getDate()+n);return d.toISOString().slice(0,10)};

export default function FinalPlanner(){
 const [lang,setLang]=useState<Lang>('ar');const t=labels[lang];const [mode,setMode]=useState<'budget'|'destination'>('budget');
 const [form,setForm]=useState<SearchInput>({origin:'Saudi Arabia|Jeddah',destination:'',region:'ALL',currency:'SAR',budget:3500,adults:1,children:0,days:5,dateMode:'anytime',searchMonths:12,startDate:todayPlus(14),flexDays:3,includeHotel:true,includeFood:true,includeLocal:true,includeActivities:true,includeEssentials:true,emergencyPct:10,tripType:'round',spendStyle:'balanced'});
 const [results,setResults]=useState<TripResult[]>([]);const [loading,setLoading]=useState(false);const [searched,setSearched]=useState(false);const [error,setError]=useState('');const [rates,setRates]=useState(fxFallback);
 const set=<K extends keyof SearchInput>(k:K,v:SearchInput[K])=>setForm(x=>({...x,[k]:v}));
 const countries=useMemo(()=>Array.from(new Set(uniqueDestinations.map(x=>x.country))),[]);const originObj=uniqueDestinations.find(x=>placeKey(x)===form.origin);const originCountry=originObj?.country||'Saudi Arabia';
 const destinations=uniqueDestinations.filter(x=>placeKey(x)!==form.origin);const name=(x:string)=>lang==='ar'?(ar[x]||x):x;const currency=form.currency||'SAR';
 const money=(sar:number)=>new Intl.NumberFormat(lang==='ar'?'ar-SA':'en-SA',{style:'currency',currency,maximumFractionDigits:['KWD','BHD','OMR'].includes(currency)?2:0}).format(sar/(rates[currency]||1));
 async function search(){setLoading(true);setError('');try{const r=await fetch('/api/search',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({...form,destination:mode==='destination'?form.destination:''})});const j=await r.json();if(!r.ok)throw new Error();setResults(j.results||[]);setRates(j.fx?.sarPerUnit||fxFallback);setSearched(true)}catch{setError(t.error)}finally{setLoading(false)}}
 const confidence=(v:CostLine['confidence'])=>v==='live'?t.live:v==='reference'?t.reference:t.allowance;
 return <main className={s.page} dir={lang==='ar'?'rtl':'ltr'} lang={lang}>
  <button className={s.lang} onClick={()=>setLang(x=>x==='ar'?'en':'ar')}>{lang==='ar'?'English':'العربية'}</button>
  <section className={s.hero}><span className={s.badge}>MIZAN · COST 2.0</span><h1>{t.title}</h1><p>{t.sub}</p></section>
  <section className={s.panel}>
   <div className={s.tabs}><button className={mode==='budget'?s.active:''} onClick={()=>setMode('budget')}>{t.budget}</button><button className={mode==='destination'?s.active:''} onClick={()=>setMode('destination')}>{t.dest}</button></div>
   <div className={s.grid}>
    <label className={s.field}><span>{t.origin}</span><select value={form.origin} onChange={e=>set('origin',e.target.value)}>{countries.map(c=><optgroup key={c} label={name(c)}>{uniqueDestinations.filter(x=>x.country===c).map(x=><option key={placeKey(x)} value={placeKey(x)}>{name(x.city)}</option>)}</optgroup>)}</select></label>
    {mode==='destination'&&<label className={s.field}><span>{t.destination}</span><select value={form.destination} onChange={e=>set('destination',e.target.value)}><option value="">—</option>{destinations.map(x=><option key={placeKey(x)} value={placeKey(x)}>{name(x.city)} · {name(x.country)}</option>)}</select></label>}
    <label className={s.field}><span>{t.money}</span><input type="number" min="1" value={form.budget} onChange={e=>set('budget',Number(e.target.value))}/></label>
    <label className={s.field}><span>Currency</span><select value={currency} onChange={e=>set('currency',e.target.value)}>{gccCurrencies.map(x=><option key={x}>{x}</option>)}</select></label>
    <label className={s.field}><span>{t.days}</span><input type="number" min="1" max="60" value={form.days} onChange={e=>set('days',Number(e.target.value))}/></label>
    <label className={s.field}><span>{t.adults}</span><input type="number" min="1" max="20" value={form.adults} onChange={e=>set('adults',Number(e.target.value))}/></label>
    <label className={s.field}><span>{t.children}</span><input type="number" min="0" max="20" value={form.children} onChange={e=>set('children',Number(e.target.value))}/></label>
    <label className={s.field}><span>{t.style}</span><select value={form.spendStyle} onChange={e=>set('spendStyle',e.target.value as SearchInput['spendStyle'])}><option value="smart">Smart / اقتصادي</option><option value="balanced">Balanced / متوازن</option><option value="comfort">Comfort / مريح</option></select></label>
    <label className={s.field}><span>{t.when}</span><select value={form.dateMode} onChange={e=>set('dateMode',e.target.value as SearchInput['dateMode'])}><option value="anytime">{t.any}</option><option value="specific">{t.specific}</option></select></label>
    {form.dateMode==='anytime'?<label className={s.field}><span>{t.window}</span><select value={form.searchMonths} onChange={e=>set('searchMonths',Number(e.target.value) as 1|3|6|12)}><option value="1">1 month</option><option value="3">3 months</option><option value="6">6 months</option><option value="12">12 months</option></select></label>:<label className={s.field}><span>{t.date}</span><input type="date" value={form.startDate} onChange={e=>set('startDate',e.target.value)}/></label>}
    <label className={s.field}><span>{t.emergency}</span><select value={form.emergencyPct??10} onChange={e=>set('emergencyPct',Number(e.target.value))}><option value="0">0%</option><option value="5">5%</option><option value="10">10%</option><option value="15">15%</option><option value="20">20%</option></select></label>
   </div>
   <div className={s.toggles}>{([['includeHotel',t.hotel],['includeFood',t.food],['includeLocal',t.local],['includeActivities',t.activities],['includeEssentials',t.essentials]] as const).map(([k,l])=><button key={k} className={`${s.chip} ${form[k]?s.active:''}`} onClick={()=>set(k,!form[k])}>{form[k]?'✓ ':''}{l}</button>)}</div>
   <button className={s.search} disabled={loading||mode==='destination'&&!form.destination} onClick={search}>{loading?t.loading:t.search}</button>
   <div className={s.notice}>{lang==='ar'?'مهم: الطيران يُوسم مباشر فقط إذا رجع من مزود حي. السكن حاليًا سعر مرجعي، والأكل والتنقل والأنشطة والضروريات مخصصات تخطيطية واضحة — وليست حجوزات وهمية.':'Important: flight prices are marked Live only when returned by a provider. Accommodation is currently reference-priced; food, transport, activities and essentials are explicit planning allowances.'}</div>
   {error&&<div className={s.notice}>{error}</div>}
  </section>
  {searched&&<section><div className={s.head}><div><h2>{t.results}</h2><div className={s.muted}>{results.length} options · {t.method}</div></div></div><div className={s.cards}>{results.length===0?<div className={s.empty}>{t.empty}</div>:results.map((r,i)=><article className={s.card} key={`${r.country}-${r.city}-${r.departure}`}>
   <div className={s.top}><div className={s.place}><div className={s.muted}>{i===0?'#1 · CHEAPEST':''}</div><h3>{name(r.city)} · {name(r.country)}</h3><div className={s.muted}>{r.departure}{r.returnDate?` → ${r.returnDate}`:''} · {r.carrier} · {r.stops===0?'Direct':`${r.stops} stop`}</div></div><div className={s.price}><strong>{money(r.costs.total)}</strong><span className={s.safe}>{t.safe}: {money(r.costs.safeTotal)}</span></div></div>
   <div className={s.summary}><div><span>{t.party}</span><b>{r.adultsCount} + {r.childrenCount} kids</b></div><div><span>{t.stay}</span><b>{r.nights} nights · {r.rooms} rooms</b></div><div><span>{t.left}</span><b className={r.remaining>=0?s.good:s.bad}>{money(r.remaining)}</b></div><div><span>{t.safe}</span><b className={r.safeWithin?s.good:s.bad}>{r.safeWithin?'✓':'+'+money(Math.abs(r.safeRemaining))}</b></div></div>
   <div className={s.trust}><span>● {r.liveFare?t.live:t.reference} flight</span><span>● {t.reference} hotel</span><span>● {t.allowance} daily costs</span><span>{r.methodologyVersion}</span></div>
   <details className={s.details}><summary>{t.details}</summary><div className={s.lines}>{r.costLines.map(line=><div className={s.line} key={line.key}><strong>{lineNames[line.key]?.[lang]||line.key}<span className={s.confidence}>{confidence(line.confidence)}</span></strong><span className={s.amount}>{money(line.amount)}</span><div className={s.explain}><span className={s.formula}>{line.formula}</span>{lang==='ar'?(explainAr[line.key]||line.basis):line.basis}</div></div>)}</div><div className={s.totals}><div><span className={s.muted}>{t.core}</span><strong>{money(r.costs.coreTotal)}</strong></div><div><span className={s.muted}>{t.safe} ({r.emergencyPct}%)</span><strong>{money(r.costs.safeTotal)}</strong></div></div></details>
  </article>)}</div></section>}
 </main>
}
