'use client';
import {useMemo,useState} from 'react';
import {ArrowRight,CalendarDays,Check,ChevronDown,CircleDollarSign,Globe2,Languages,MapPin,Plane,RefreshCw,SlidersHorizontal,Sparkles,Users,WalletCards} from 'lucide-react';
import {uniqueDestinations} from '@/lib/destinations';
import type {Region,SearchInput,TripResult} from '@/lib/types';

type Lang='en'|'ar';
type SortMode='best'|'cheapest'|'remaining';

const copy={
  en:{planner:'Planner',results:'Results',how:'How it works',budgetFirst:'BUDGET-FIRST TRAVEL',hero1:'Start with the budget.',hero2:'Then choose the trip.',heroP:'MIZAN compares the full cost of a trip — flights, stay, food, local transport and experiences — across Saudi Arabia, the GCC and Arab destinations.',saudi:'Saudi Arabia',gcc:'GCC',arab:'Arab world',multi:'Multi-currency',haveBudget:'I have a budget',knowDestination:'I know my destination',tripBuilder:'TRIP BUILDER',budgetQ:'How far can your budget take you?',destQ:'Find the best total for this destination.',traveler:'traveler',travelers:'travelers',from:'FROM',region:'SEARCH REGION',destination:'DESTINATION',budget:'TOTAL BUDGET',departure:'DEPARTURE',length:'TRIP LENGTH',adults:'ADULTS',children:'CHILDREN',flex:'DATE FLEXIBILITY',style:'SPENDING STYLE',tripType:'TRIP TYPE',all:'All supported destinations',choose:'Choose a destination',days:'days',exact:'Exact dates',smart:'Smart / value',balanced:'Balanced',comfort:'Comfort',round:'Round trip',oneway:'One way',include:'Include in trip total',stay:'Stay',food:'Food',local:'Local transport',experiences:'Experiences',chooseHint:'Choose a destination before searching.',searching:'Calculating the full trip…',find:'Find trips within my budget',compare:'Compare this destination',tripOptions:'TRIP OPTIONS',fit:(n:number)=>`${n} options fit your budget`,closest:'Closest options to your budget',live:'Live flight fares + reference trip costs',reference:'Reference fare model',fx:'FX',liveRates:'live daily rates',refRates:'reference rates',bestMatch:'BEST MATCH',total:'TOTAL',budgetLabel:'BUDGET',left:'left',over:'over',used:'used',sort:'Sort',best:'Best match',cheapest:'Cheapest total',mostLeft:'Most budget left',direct:'Direct',stop:'stop',liveFare:'live fare',refFare:'reference fare',transport:'Transport',localCurrency:'Local currency',estimated:'Estimated trip total',perTraveler:'per traveler',room:'room',rooms:'rooms',disclaimer:'Flight fares use live Amadeus data when API credentials are connected; otherwise MIZAN uses a deterministic reference-price model for planning. Accommodation and daily-cost estimates are planning estimates, not booking quotes.',why:'WHY MIZAN',whyTitle:'A travel search that starts where real decisions start.',h1:'Budget first',h1p:'Search from the amount you can actually spend instead of discovering the total after choosing a destination.',h2:'Whole-trip math',h2p:'Flights, rooms, food, transport and experiences are normalized into SAR for one comparable total.',h3:'Flexible-date engine',h3p:'Nearby departure dates are evaluated because moving a trip by one or three days can change the final cost.',h4:'Family-aware',h4p:'Adult and child counts affect flights, room count and daily spending instead of multiplying one generic price.',footer:'Budget-first trip planning for Saudi Arabia, the GCC and the Arab world.'},
  ar:{planner:'المخطط',results:'النتائج',how:'كيف يعمل',budgetFirst:'السفر يبدأ من ميزانيتك',hero1:'ابدأ بالميزانية.',hero2:'ثم اختر الرحلة.',heroP:'ميزان يقارن التكلفة الكاملة للرحلة — الطيران، السكن، الطعام، التنقل المحلي والتجارب — داخل السعودية والخليج والدول العربية.',saudi:'السعودية',gcc:'الخليج',arab:'الدول العربية',multi:'عملات متعددة',haveBudget:'عندي ميزانية',knowDestination:'أعرف وجهتي',tripBuilder:'مخطط الرحلة',budgetQ:'إلى أين يمكن أن توصلك ميزانيتك؟',destQ:'اعثر على أفضل تكلفة كاملة لهذه الوجهة.',traveler:'مسافر',travelers:'مسافرين',from:'من',region:'نطاق البحث',destination:'الوجهة',budget:'الميزانية الإجمالية',departure:'تاريخ المغادرة',length:'مدة الرحلة',adults:'البالغون',children:'الأطفال',flex:'مرونة التاريخ',style:'نمط الصرف',tripType:'نوع الرحلة',all:'كل الوجهات المدعومة',choose:'اختر وجهة',days:'أيام',exact:'نفس التاريخ',smart:'اقتصادي',balanced:'متوازن',comfort:'مريح',round:'ذهاب وعودة',oneway:'ذهاب فقط',include:'أدخل ضمن إجمالي الرحلة',stay:'السكن',food:'الطعام',local:'التنقل المحلي',experiences:'الأنشطة والتجارب',chooseHint:'اختر الوجهة قبل البحث.',searching:'جاري حساب الرحلة كاملة…',find:'ابحث ضمن ميزانيتي',compare:'قارن تكلفة هذه الوجهة',tripOptions:'خيارات الرحلات',fit:(n:number)=>`${n} خيار ضمن ميزانيتك`,closest:'أقرب الخيارات لميزانيتك',live:'أسعار طيران مباشرة + تقديرات بقية الرحلة',reference:'نموذج أسعار مرجعي',fx:'العملة',liveRates:'أسعار يومية مباشرة',refRates:'أسعار مرجعية',bestMatch:'أفضل تطابق',total:'الإجمالي',budgetLabel:'الميزانية',left:'متبقي',over:'زيادة',used:'مستخدم',sort:'الترتيب',best:'أفضل تطابق',cheapest:'الأرخص إجمالًا',mostLeft:'أكثر مبلغ متبقّي',direct:'مباشرة',stop:'توقف',liveFare:'سعر مباشر',refFare:'سعر مرجعي',transport:'التنقل',localCurrency:'العملة المحلية',estimated:'إجمالي الرحلة التقديري',perTraveler:'لكل مسافر',room:'غرفة',rooms:'غرف',disclaimer:'تستخدم أسعار الطيران بيانات Amadeus المباشرة عند ربط بيانات الدخول. بدونها يستخدم ميزان نموذجًا مرجعيًا للتخطيط. أسعار السكن والمصاريف اليومية تقديرية وليست عروض حجز نهائية.',why:'لماذا ميزان؟',whyTitle:'بحث سفر يبدأ من النقطة التي تبدأ منها القرارات الحقيقية.',h1:'الميزانية أولًا',h1p:'ابدأ بالمبلغ الذي يمكنك إنفاقه فعلًا بدل معرفة الإجمالي بعد اختيار الوجهة.',h2:'حساب الرحلة كاملة',h2p:'الطيران والسكن والطعام والتنقل والتجارب تُحوّل إلى الريال السعودي في إجمالي واحد قابل للمقارنة.',h3:'مرونة التواريخ',h3p:'يختبر ميزان التواريخ القريبة لأن تغيير يوم أو ثلاثة أيام قد يغيّر التكلفة النهائية.',h4:'مناسب للعائلات',h4p:'عدد البالغين والأطفال يؤثر على الطيران وعدد الغرف والمصاريف اليومية بدل ضرب سعر موحد.',footer:'تخطيط رحلات حسب الميزانية للسعودية والخليج والدول العربية.'}
};

const money=(n:number,lang:Lang)=>new Intl.NumberFormat(lang==='ar'?'ar-SA':'en-SA',{style:'currency',currency:'SAR',maximumFractionDigits:0}).format(n);
const dateLabel=(v:string,lang:Lang)=>new Intl.DateTimeFormat(lang==='ar'?'ar-SA':'en-GB',{day:'numeric',month:'short'}).format(new Date(`${v}T12:00:00Z`));
const inTwoWeeks=()=>{const d=new Date();d.setDate(d.getDate()+14);return d.toISOString().slice(0,10)};
const regionLabel=(r:string,lang:Lang)=>lang==='ar'?(r==='Saudi Arabia'?'السعودية':r==='GCC'?'الخليج':r==='Arab World'?'الدول العربية':r):r;

export default function TravelPlanner(){
  const [lang,setLang]=useState<Lang>('en'); const t=copy[lang];
  const [mode,setMode]=useState<'budget'|'destination'>('budget'); const [sortMode,setSortMode]=useState<SortMode>('best');
  const [form,setForm]=useState<SearchInput>({origin:'JED',destination:'',region:'ALL',budget:3500,adults:1,children:0,days:5,startDate:inTwoWeeks(),flexDays:3,includeHotel:true,includeFood:true,includeLocal:true,includeActivities:true,tripType:'round',spendStyle:'balanced'});
  const [results,setResults]=useState<TripResult[]>([]); const [loading,setLoading]=useState(false); const [searched,setSearched]=useState(false); const [error,setError]=useState(''); const [meta,setMeta]=useState<{source?:string;fxSource?:string}>({});
  const set=<K extends keyof SearchInput>(k:K,v:SearchInput[K])=>setForm(x=>({...x,[k]:v})); const party=form.adults+form.children;
  const within=useMemo(()=>results.filter(r=>r.within),[results]); const sortedResults=useMemo(()=>[...results].sort((a,b)=>sortMode==='cheapest'?a.costs.total-b.costs.total:sortMode==='remaining'?b.remaining-a.remaining:b.score-a.score),[results,sortMode]);
  const best=sortedResults.find(r=>r.within)||sortedResults[0]; const origins=uniqueDestinations.filter(d=>d.region==='Saudi Arabia'); const visibleDestinations=uniqueDestinations.filter(d=>form.region==='ALL'||d.region===form.region);
  async function search(){setLoading(true);setError('');setSearched(false);try{const res=await fetch('/api/search',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({...form,destination:mode==='destination'?form.destination:''})});const json=await res.json();if(!res.ok)throw new Error(json.error||'Search failed');setResults(json.results||[]);setMeta({source:json.source,fxSource:json.fx?.source});setSearched(true)}catch(e){setError(e instanceof Error?e.message:'Search failed')}finally{setLoading(false)}}

  return <main dir={lang==='ar'?'rtl':'ltr'} lang={lang} className={lang==='ar'?'rtl':''}>
    <header className="topbar"><a className="brand" href="#top"><span className="mark">M</span><span>MIZAN</span></a><nav><a href="#planner">{t.planner}</a><a href="#results">{t.results}</a><a href="#how">{t.how}</a></nav><div className="headerActions"><button className="language" onClick={()=>setLang(x=>x==='en'?'ar':'en')}><Languages size={16}/>{lang==='en'?'العربية':'English'}</button><div className="currency">SAR <ChevronDown size={14}/></div></div></header>
    <section id="top" className="hero shell"><div className="eyebrow"><Sparkles size={15}/> {t.budgetFirst}</div><h1>{t.hero1}<br/><em>{t.hero2}</em></h1><p>{t.heroP}</p><div className="scope"><span><Check/> {t.saudi}</span><span><Check/> {t.gcc}</span><span><Check/> {t.arab}</span><span><Globe2/> {t.multi}</span></div></section>
    <section id="planner" className="planner shell"><div className="modeTabs"><button className={mode==='budget'?'active':''} onClick={()=>setMode('budget')}>{t.haveBudget}</button><button className={mode==='destination'?'active':''} onClick={()=>setMode('destination')}>{t.knowDestination}</button></div><div className="plannerIntro"><div><small>{t.tripBuilder}</small><h2>{mode==='budget'?t.budgetQ:t.destQ}</h2></div><div className="partyPill"><Users size={16}/>{party} {party===1?t.traveler:t.travelers}</div></div>
      <div className="formGrid">
        <Field label={t.from} icon={<MapPin/>}><select value={form.origin} onChange={e=>set('origin',e.target.value)}>{origins.map(d=><option key={d.iata} value={d.iata}>{d.city} ({d.iata})</option>)}</select></Field>
        {mode==='budget'?<Field label={t.region} icon={<Globe2/>}><select value={form.region} onChange={e=>set('region',e.target.value as 'ALL'|Region)}><option value="ALL">{t.all}</option><option value="Saudi Arabia">{regionLabel('Saudi Arabia',lang)}</option><option value="GCC">{regionLabel('GCC',lang)}</option><option value="Arab World">{regionLabel('Arab World',lang)}</option></select></Field>:<Field label={t.destination} icon={<Plane/>}><select value={form.destination} onChange={e=>set('destination',e.target.value)}><option value="">{t.choose}</option>{visibleDestinations.map(d=><option key={d.iata} value={d.iata}>{d.city}, {d.country}</option>)}</select></Field>}
        <Field label={t.budget} icon={<WalletCards/>}><input type="number" min="100" step="100" value={form.budget} onChange={e=>set('budget',Number(e.target.value))}/><b>SAR</b></Field>
        <Field label={t.departure} icon={<CalendarDays/>}><input type="date" value={form.startDate} min={new Date().toISOString().slice(0,10)} onChange={e=>set('startDate',e.target.value)}/></Field>
        <Field label={t.length} icon={<CalendarDays/>}><input type="number" min="1" max="60" value={form.days} onChange={e=>set('days',Number(e.target.value))}/><b>{t.days}</b></Field>
        <Field label={t.tripType} icon={<Plane/>}><select value={form.tripType} onChange={e=>set('tripType',e.target.value as SearchInput['tripType'])}><option value="round">{t.round}</option><option value="oneway">{t.oneway}</option></select></Field>
        <Field label={t.adults} icon={<Users/>}><input type="number" min="1" max="20" value={form.adults} onChange={e=>set('adults',Number(e.target.value))}/></Field><Field label={t.children} icon={<Users/>}><input type="number" min="0" max="20" value={form.children} onChange={e=>set('children',Number(e.target.value))}/></Field>
        <Field label={t.flex} icon={<RefreshCw/>}><select value={form.flexDays} onChange={e=>set('flexDays',Number(e.target.value))}><option value="0">{t.exact}</option><option value="1">± 1 {lang==='ar'?'يوم':'day'}</option><option value="3">± 3 {t.days}</option><option value="7">± 7 {t.days}</option></select></Field>
        <Field label={t.style} icon={<CircleDollarSign/>}><select value={form.spendStyle} onChange={e=>set('spendStyle',e.target.value as SearchInput['spendStyle'])}><option value="smart">{t.smart}</option><option value="balanced">{t.balanced}</option><option value="comfort">{t.comfort}</option></select></Field>
      </div>
      <div className="optionsBar"><div className="optionsTitle"><SlidersHorizontal size={17}/><strong>{t.include}</strong></div>{([['includeHotel',t.stay],['includeFood',t.food],['includeLocal',t.local],['includeActivities',t.experiences]] as const).map(([k,l])=><label className="toggleChip" key={k}><input type="checkbox" checked={form[k]} onChange={e=>set(k,e.target.checked)}/><span>{l}</span></label>)}</div>{mode==='destination'&&!form.destination&&<p className="hint">{t.chooseHint}</p>}{error&&<p className="error">{error}</p>}<button className="searchButton" onClick={search} disabled={loading||(mode==='destination'&&!form.destination)}>{loading?t.searching:mode==='budget'?t.find:t.compare} <ArrowRight size={18}/></button>
    </section>
    {searched&&<section id="results" className="results shell"><div className="resultsHead"><div><small>{t.tripOptions}</small><h2>{within.length?t.fit(within.length):t.closest}</h2></div><div className="resultControls"><div className="sourceNotes"><span>{meta.source==='live+reference'?t.live:t.reference}</span><span>{t.fx}: {meta.fxSource==='live'?t.liveRates:t.refRates}</span></div><label className="sortSelect">{t.sort}<select value={sortMode} onChange={e=>setSortMode(e.target.value as SortMode)}><option value="best">{t.best}</option><option value="cheapest">{t.cheapest}</option><option value="remaining">{t.mostLeft}</option></select></label></div></div>
      {best&&<div className="bestSummary"><div><small>{t.bestMatch}</small><strong>{best.city}</strong><span>{best.country}</span></div><div><small>{t.total}</small><strong>{money(best.costs.total,lang)}</strong><span>{money(best.costs.perPerson,lang)} / {t.perTraveler}</span></div><div><small>{t.budgetLabel}</small><strong>{best.within?`${money(best.remaining,lang)} ${t.left}`:`${money(-best.remaining,lang)} ${t.over}`}</strong><span>{best.budgetUsage}% {t.used}</span></div></div>}
      <div className="cards">{sortedResults.map((r,i)=><TripCard key={`${r.iata}-${r.departure}-${i}`} result={r} rank={i+1} lang={lang} t={t}/>)}</div><p className="disclaimer">{t.disclaimer}</p></section>}
    <section id="how" className="how"><div className="shell"><small>{t.why}</small><h2>{t.whyTitle}</h2><div className="howGrid"><article><b>01</b><h3>{t.h1}</h3><p>{t.h1p}</p></article><article><b>02</b><h3>{t.h2}</h3><p>{t.h2p}</p></article><article><b>03</b><h3>{t.h3}</h3><p>{t.h3p}</p></article><article><b>04</b><h3>{t.h4}</h3><p>{t.h4p}</p></article></div></div></section><footer><div className="shell footerInner"><div className="brand"><span className="mark">M</span><span>MIZAN</span></div><p>{t.footer}</p></div></footer>
  </main>
}
function Field({label,icon,children}:{label:string;icon:React.ReactNode;children:React.ReactNode}){return <label className="field"><small>{label}</small><div>{icon}{children}</div></label>}
function TripCard({result:r,rank,lang,t}:{result:TripResult;rank:number;lang:Lang;t:typeof copy.en}){return <article className="tripCard"><div className="cardTop"><div><span className="rank">#{String(rank).padStart(2,'0')}</span><h3>{r.city}</h3><p>{r.country} · {dateLabel(r.departure,lang)}{r.returnDate?` → ${dateLabel(r.returnDate,lang)}`:''}</p></div><span className={r.within?'fit':'over'}>{r.within?`${money(r.remaining,lang)} ${t.left}`:`${money(-r.remaining,lang)} ${t.over}`}</span></div><div className="flightLine"><Plane size={18}/><div><b>{r.carrier}</b><small>{r.stops?`${r.stops} ${t.stop}`:t.direct} · {r.liveFare?t.liveFare:t.refFare}</small></div><strong>{money(r.costs.flight,lang)}</strong></div><div className="breakdown"><span>{t.stay} <b>{money(r.costs.hotel,lang)}</b></span><span>{t.food} <b>{money(r.costs.food,lang)}</b></span><span>{t.transport} <b>{money(r.costs.local,lang)}</b></span><span>{t.experiences} <b>{money(r.costs.activities,lang)}</b></span></div><div className="currencyLine">{t.localCurrency}: <b>{r.nativeCurrency}</b> · 1 {r.nativeCurrency} ≈ {r.fxRateToSar.toFixed(r.fxRateToSar<0.1?3:2)} SAR</div><div className="total"><div><span>{t.estimated}</span><small>{money(r.costs.perPerson,lang)} {t.perTraveler} · {r.rooms} {r.rooms===1?t.room:t.rooms}</small></div><strong>{money(r.costs.total,lang)}</strong></div><div className="budgetTrack"><i style={{width:`${Math.min(100,r.budgetUsage)}%`}} className={r.within?'ok':'danger'}/></div></article>}
