'use client';
import {useMemo,useState} from 'react';
import {Check,Languages} from 'lucide-react';
import {gccCurrencies,placeKey,uniqueDestinations} from '@/lib/destinations';
import type {SearchInput,TripResult,CostLine} from '@/lib/types';
import s from './TravelPlanner.module.css';

type Lang='en'|'ar';
type SortMode='cheapest'|'remaining'|'best';
type AddonId='roaming'|'esim'|'local-sim'|'baggage'|'insurance'|'airport-transfer'|'driver'|'guide'|'car-rental';

type Addon={id:AddonId;icon:string;group?:'internet';name:{en:string;ar:string};description:{en:string;ar:string};basis:{en:string;ar:string};price:(trip:TripResult)=>number};

const fallbackSarPerUnit:Record<string,number>={SAR:1,AED:1.021,QAR:1.03,KWD:12.2,BHD:9.95,OMR:9.75};
const inTwoWeeks=()=>{const d=new Date();d.setDate(d.getDate()+14);return d.toISOString().slice(0,10)};
const money=(sar:number,lang:Lang,currency:string,rates:Record<string,number>)=>{const rate=rates[currency]||fallbackSarPerUnit[currency]||1;return new Intl.NumberFormat(lang==='ar'?'ar-SA':'en-SA',{style:'currency',currency,maximumFractionDigits:['KWD','BHD','OMR'].includes(currency)?2:0}).format(sar/rate)};
const dateLabel=(v:string,lang:Lang)=>new Intl.DateTimeFormat(lang==='ar'?'ar-SA':'en-GB',{day:'numeric',month:'short',year:'numeric'}).format(new Date(`${v}T12:00:00Z`));
const arNames:Record<string,string>={'Saudi Arabia':'السعودية','United Arab Emirates':'الإمارات','Qatar':'قطر','Kuwait':'الكويت','Bahrain':'البحرين','Oman':'عُمان','Jeddah':'جدة','Riyadh':'الرياض','Dammam':'الدمام','Madinah':'المدينة المنورة','Makkah':'مكة المكرمة','Abha':'أبها','Taif':'الطائف','AlUla':'العلا','Tabuk':'تبوك','Jazan':'جازان','Yanbu':'ينبع','Al Baha':'الباحة','Hail':'حائل','Qassim':'القصيم','Najran':'نجران','Al Ahsa':'الأحساء','Sakaka':'سكاكا','Arar':'عرعر','Khobar':'الخبر','Jubail':'الجبيل','Dubai':'دبي','Abu Dhabi':'أبوظبي','Sharjah':'الشارقة','Ras Al Khaimah':'رأس الخيمة','Al Ain':'العين','Fujairah':'الفجيرة','Doha':'الدوحة','Kuwait City':'مدينة الكويت','Manama':'المنامة','Muharraq':'المحرق','Muscat':'مسقط','Salalah':'صلالة','Sohar':'صحار','Duqm':'الدقم','Egypt':'مصر','Cairo':'القاهرة','Alexandria':'الإسكندرية','Jordan':'الأردن','Amman':'عمّان','Aqaba':'العقبة','Lebanon':'لبنان','Beirut':'بيروت','Morocco':'المغرب','Casablanca':'الدار البيضاء','Marrakech':'مراكش','Tunisia':'تونس','Tunis':'تونس','Algeria':'الجزائر','Algiers':'الجزائر','Oran':'وهران','Iraq':'العراق','Baghdad':'بغداد','Erbil':'أربيل','Palestine':'فلسطين','Libya':'ليبيا','Syria':'سوريا','Yemen':'اليمن','Sudan':'السودان','Djibouti':'جيبوتي','Somalia':'الصومال','Mauritania':'موريتانيا','Comoros':'جزر القمر'};
const label=(v:string,lang:Lang)=>lang==='ar'?(arNames[v]||v):v;

const addons:Addon[]=[
 {id:'roaming',icon:'📶',group:'internet',name:{en:'Roaming on your current SIM',ar:'تجوال على شريحتك الحالية'},description:{en:'Keep your existing number and use a travel roaming bundle.',ar:'تحتفظ برقمك الحالي وتستخدم باقة تجوال أثناء الرحلة.'},basis:{en:'Planning estimate: SAR 35 per traveler/day.',ar:'تقدير تخطيطي: ٣٥ ر.س لكل مسافر/يوم.'},price:t=>Math.round(35*t.days*t.travelers)},
 {id:'esim',icon:'🌐',group:'internet',name:{en:'Travel eSIM',ar:'شريحة eSIM للسفر'},description:{en:'Data-only eSIM, useful when you want internet without replacing your physical SIM.',ar:'شريحة بيانات إلكترونية مناسبة للإنترنت بدون تغيير شريحتك الأساسية.'},basis:{en:'Planning estimate: SAR 18 per traveler/day.',ar:'تقدير تخطيطي: ١٨ ر.س لكل مسافر/يوم.'},price:t=>Math.round(18*t.days*t.travelers)},
 {id:'local-sim',icon:'📱',group:'internet',name:{en:'Local SIM',ar:'شريحة محلية'},description:{en:'Local prepaid SIM estimate for the destination.',ar:'تقدير لشريحة محلية مسبقة الدفع في الوجهة.'},basis:{en:'SAR 45 setup + SAR 8/day per traveler.',ar:'٤٥ ر.س للشريحة + ٨ ر.س يوميًا لكل مسافر.'},price:t=>Math.round((45+8*t.days)*t.travelers)},
 {id:'baggage',icon:'🧳',name:{en:'Extra baggage',ar:'أمتعة إضافية'},description:{en:'Allowance for one extra checked-bag service per traveler.',ar:'مخصص تقديري لخدمة حقيبة شحن إضافية لكل مسافر.'},basis:{en:'Reference allowance: SAR 120 per traveler.',ar:'مخصص مرجعي: ١٢٠ ر.س لكل مسافر.'},price:t=>120*t.travelers},
 {id:'insurance',icon:'🛡️',name:{en:'Travel insurance',ar:'تأمين سفر'},description:{en:'Basic travel insurance planning allowance for the party.',ar:'مخصص تخطيطي لتأمين سفر أساسي للمجموعة.'},basis:{en:'SAR 9 per traveler/day.',ar:'٩ ر.س لكل مسافر/يوم.'},price:t=>9*t.days*t.travelers},
 {id:'airport-transfer',icon:'🚐',name:{en:'Airport transfer',ar:'استقبال ونقل من/إلى المطار'},description:{en:'Private arrival and departure transfer estimate.',ar:'تقدير لنقل خاص عند الوصول والمغادرة.'},basis:{en:'Reference allowance: SAR 90 each way.',ar:'مخصص مرجعي: ٩٠ ر.س لكل اتجاه.'},price:t=>t.returnDate?180:90},
 {id:'driver',icon:'🚘',name:{en:'Private driver',ar:'سائق خاص'},description:{en:'Dedicated family/private driver for local movement.',ar:'سائق خاص للعائلة أو المجموعة للتنقل داخل الوجهة.'},basis:{en:'Planning estimate: SAR 320/day.',ar:'تقدير تخطيطي: ٣٢٠ ر.س يوميًا.'},price:t=>320*t.days},
 {id:'guide',icon:'🧭',name:{en:'Private guide',ar:'مرشد خاص'},description:{en:'Private guide for a structured day plan and language support.',ar:'مرشد خاص للبرنامج اليومي والمساعدة في التواصل.'},basis:{en:'Planning estimate: SAR 280/day.',ar:'تقدير تخطيطي: ٢٨٠ ر.س يوميًا.'},price:t=>280*t.days},
 {id:'car-rental',icon:'🚗',name:{en:'Rental car',ar:'تأجير سيارة'},description:{en:'Standard rental-car allowance; fuel and deposits are not included.',ar:'مخصص تقديري لسيارة إيجار عادية؛ الوقود والتأمينات المستردة غير مشمولة.'},basis:{en:'Reference allowance: SAR 170/day.',ar:'مخصص مرجعي: ١٧٠ ر.س يوميًا.'},price:t=>170*t.days}
];

const lineName=(key:CostLine['key'],lang:Lang)=>({en:{flight:'Flights',hotel:'Stay',food:'Food',local:'Local transport',activities:'Activities',essentials:'Essentials',emergency:'Emergency reserve'},ar:{flight:'الطيران',hotel:'السكن',food:'الأكل',local:'التنقل المحلي',activities:'الأنشطة والتجارب',essentials:'الضروريات',emergency:'احتياطي الطوارئ'}}[lang][key]);
const confidence=(c:CostLine['confidence'],lang:Lang)=>lang==='ar'?(c==='live'?'مباشر':c==='reference'?'مرجعي':'تقديري'):(c==='live'?'Live':c==='reference'?'Reference':'Estimated');

export default function TravelPlanner(){
 const [lang,setLang]=useState<Lang>('ar');
 const [mode,setMode]=useState<'budget'|'destination'>('budget');
 const [sortMode,setSortMode]=useState<SortMode>('cheapest');
 const [originCountry,setOriginCountry]=useState('Saudi Arabia');
 const [destinationCountry,setDestinationCountry]=useState('United Arab Emirates');
 const [form,setForm]=useState<SearchInput>({origin:'Saudi Arabia|Jeddah',destination:'United Arab Emirates|Dubai',region:'ALL',currency:'SAR',budget:5000,adults:1,children:0,days:5,dateMode:'anytime',searchMonths:12,startDate:inTwoWeeks(),flexDays:3,includeHotel:true,includeFood:true,includeLocal:true,includeActivities:true,includeEssentials:true,emergencyPct:10,tripType:'round',spendStyle:'balanced'});
 const [results,setResults]=useState<TripResult[]>([]);
 const [meta,setMeta]=useState<{source?:string;fxSource?:string;sarPerUnit:Record<string,number>;datesScanned?:number}>({sarPerUnit:fallbackSarPerUnit});
 const [loading,setLoading]=useState(false);const [searched,setSearched]=useState(false);const [error,setError]=useState('');
 const [details,setDetails]=useState<string|null>(null);const [selectedTrip,setSelectedTrip]=useState<TripResult|null>(null);const [selectedAddons,setSelectedAddons]=useState<AddonId[]>([]);
 const set=<K extends keyof SearchInput>(k:K,v:SearchInput[K])=>setForm(x=>({...x,[k]:v}));
 const currency=form.currency||'SAR';const moneyNow=(v:number)=>money(v,lang,currency,meta.sarPerUnit);
 const budgetSar=form.budget*(meta.sarPerUnit[currency]||1);
 const supportedCountries=useMemo(()=>Array.from(new Set(uniqueDestinations.map(d=>d.country))),[]);
 const originCities=uniqueDestinations.filter(d=>d.country===originCountry);
 const visibleDestinations=uniqueDestinations.filter(d=>form.region==='ALL'||d.region===form.region);
 const destinationCountries=Array.from(new Set(visibleDestinations.map(d=>d.country)));
 const destinationCities=visibleDestinations.filter(d=>d.country===destinationCountry);
 const sorted=useMemo(()=>[...results].sort((a,b)=>sortMode==='remaining'?b.remaining-a.remaining:sortMode==='best'?b.score-a.score:a.costs.total-b.costs.total),[results,sortMode]);
 const within=results.filter(r=>r.within).length;
 const selectedAddonRows=selectedTrip?addons.filter(a=>selectedAddons.includes(a.id)).map(a=>({...a,amount:a.price(selectedTrip)})):[];
 const addonTotal=selectedAddonRows.reduce((n,a)=>n+a.amount,0);
 const finalTotal=(selectedTrip?.costs.total||0)+addonTotal;
 const reserve=selectedTrip?Math.round(finalTotal*selectedTrip.emergencyPct/100):0;
 const safeFinal=finalTotal+reserve;const finalRemaining=budgetSar-finalTotal;const safeRemaining=budgetSar-safeFinal;
 function chooseOriginCountry(country:string){setOriginCountry(country);const first=uniqueDestinations.find(d=>d.country===country);if(first)set('origin',placeKey(first))}
 function chooseDestinationCountry(country:string){setDestinationCountry(country);const first=visibleDestinations.find(d=>d.country===country);if(first)set('destination',placeKey(first))}
 async function search(){setLoading(true);setError('');setSearched(false);setSelectedTrip(null);try{const res=await fetch('/api/search',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({...form,destination:mode==='destination'?form.destination:''})});const json=await res.json();if(!res.ok)throw new Error(json.error||'Search failed');setResults(json.results||[]);setMeta({source:json.source,fxSource:json.fx?.source,sarPerUnit:json.fx?.sarPerUnit||fallbackSarPerUnit,datesScanned:json.datesScanned});setSortMode('cheapest');setSearched(true)}catch(e){setError(e instanceof Error?e.message:'Search failed')}finally{setLoading(false)}}
 function openTrip(trip:TripResult){setSelectedTrip(trip);setSelectedAddons([])}
 function toggleAddon(addon:Addon){setSelectedAddons(prev=>{if(prev.includes(addon.id))return prev.filter(x=>x!==addon.id);let next=[...prev];if(addon.group==='internet')next=next.filter(id=>!addons.find(a=>a.id===id)?.group);return [...next,addon.id]})}
 const ar=lang==='ar';
 return <main dir={ar?'rtl':'ltr'} lang={lang} className={s.page}>
  {loading&&<div className={s.loadingOverlay}><div className={s.loader}><div className={s.orbit}><div/></div><strong>MIZAN</strong><small>{ar?'نبحث عن أوفر رحلة ونحسبها لك…':'Finding and calculating your best-value trips…'}</small></div></div>}
  <div className={`${s.shell} ${s.top}`}><a className={s.brand} href="#top"><i className={s.logo}/><span>MIZAN</span></a><div className={s.actions}><button className={s.ghost} onClick={()=>setLang(ar?'en':'ar')}><Languages size={15}/> {ar?'English':'العربية'}</button><select className={s.select} value={currency} onChange={e=>set('currency',e.target.value)}>{gccCurrencies.map(c=><option key={c}>{c}</option>)}</select></div></div>
  <section id="top" className={`${s.shell} ${s.hero}`}><div className={s.eyebrow}>{ar?'رحلتك موزونة على ميزانيتك':'BUDGET-FIRST TRAVEL'}</div><h1>{ar?'اعرف تكلفة الرحلة ':'Know the trip cost '}<em>{ar?'قبل ما تبدأ.':'before you go.'}</em></h1><p>{ar?'ميزان يبحث عن الرحلات ويرتبها من الأرخص، ثم يوضح لك كيف انحسب كل ريال. وبعد اختيار الرحلة تقدر تضيف خدماتك بشكل مستقل وتشوف الإجمالي النهائي والمتبقي من ميزانيتك.':'MIZAN ranks trips by total core cost, explains how every amount was calculated, then lets you customize the selected trip with optional services and see your final total.'}</p></section>
  <section className={`${s.shell} ${s.planner}`}>
   <div className={s.tabs}><button className={mode==='budget'?s.active:''} onClick={()=>setMode('budget')}>{ar?'عندي ميزانية':'I have a budget'}</button><button className={mode==='destination'?s.active:''} onClick={()=>setMode('destination')}>{ar?'أعرف وجهتي':'I know my destination'}</button></div>
   <div className={s.grid}>
    <Field title={ar?'من دولة':'FROM COUNTRY'}><select value={originCountry} onChange={e=>chooseOriginCountry(e.target.value)}>{supportedCountries.map(x=><option key={x} value={x}>{label(x,lang)}</option>)}</select></Field>
    <Field title={ar?'من مدينة':'FROM CITY'}><select value={form.origin} onChange={e=>set('origin',e.target.value)}>{originCities.map(d=><option key={placeKey(d)} value={placeKey(d)}>{label(d.city,lang)}</option>)}</select></Field>
    {mode==='budget'?<Field title={ar?'نطاق البحث':'SEARCH REGION'}><select value={form.region} onChange={e=>set('region',e.target.value as SearchInput['region'])}><option value="ALL">{ar?'كل الوجهات':'All destinations'}</option><option value="Saudi Arabia">{ar?'السعودية':'Saudi Arabia'}</option><option value="GCC">{ar?'الخليج':'GCC'}</option><option value="Arab World">{ar?'الدول العربية':'Arab world'}</option></select></Field>:<><Field title={ar?'دولة الوجهة':'DESTINATION COUNTRY'}><select value={destinationCountry} onChange={e=>chooseDestinationCountry(e.target.value)}>{destinationCountries.map(x=><option key={x}>{x}</option>)}</select></Field><Field title={ar?'مدينة الوجهة':'DESTINATION CITY'}><select value={form.destination} onChange={e=>set('destination',e.target.value)}>{destinationCities.map(d=><option key={placeKey(d)} value={placeKey(d)}>{label(d.city,lang)}</option>)}</select></Field></>}
    <Field title={ar?'الميزانية الإجمالية':'TOTAL BUDGET'}><input type="number" min="1" value={form.budget} onChange={e=>set('budget',Number(e.target.value))}/></Field>
    <Field title={ar?'عدد الأيام':'TRIP DAYS'}><input type="number" min="1" max="60" value={form.days} onChange={e=>set('days',Number(e.target.value))}/></Field>
    <Field title={ar?'البالغون':'ADULTS'}><input type="number" min="1" max="20" value={form.adults} onChange={e=>set('adults',Number(e.target.value))}/></Field>
    <Field title={ar?'الأطفال':'CHILDREN'}><input type="number" min="0" max="20" value={form.children} onChange={e=>set('children',Number(e.target.value))}/></Field>
    <Field title={ar?'موعد السفر':'WHEN'}><select value={form.dateMode} onChange={e=>set('dateMode',e.target.value as SearchInput['dateMode'])}><option value="anytime">{ar?'أي وقت — دور الأرخص':'Anytime — find cheapest'}</option><option value="specific">{ar?'تاريخ محدد':'Specific date'}</option></select></Field>
    {form.dateMode==='anytime'?<Field title={ar?'فترة البحث':'SEARCH WINDOW'}><select value={form.searchMonths} onChange={e=>set('searchMonths',Number(e.target.value) as 1|3|6|12)}><option value={1}>{ar?'شهر':'1 month'}</option><option value={3}>{ar?'٣ أشهر':'3 months'}</option><option value={6}>{ar?'٦ أشهر':'6 months'}</option><option value={12}>{ar?'١٢ شهر':'12 months'}</option></select></Field>:<Field title={ar?'تاريخ المغادرة':'DEPARTURE'}><input type="date" value={form.startDate} onChange={e=>set('startDate',e.target.value)}/></Field>}
    <Field title={ar?'نمط الصرف':'SPENDING STYLE'}><select value={form.spendStyle} onChange={e=>set('spendStyle',e.target.value as SearchInput['spendStyle'])}><option value="smart">{ar?'اقتصادي':'Smart / value'}</option><option value="balanced">{ar?'متوازن':'Balanced'}</option><option value="comfort">{ar?'مريح':'Comfort'}</option></select></Field>
    <Field title={ar?'نوع الرحلة':'TRIP TYPE'}><select value={form.tripType} onChange={e=>set('tripType',e.target.value as SearchInput['tripType'])}><option value="round">{ar?'ذهاب وعودة':'Round trip'}</option><option value="oneway">{ar?'ذهاب فقط':'One way'}</option></select></Field>
    <Field title={ar?'احتياطي الطوارئ':'EMERGENCY RESERVE'}><select value={form.emergencyPct??10} onChange={e=>set('emergencyPct',Number(e.target.value))}>{[0,5,10,15,20].map(x=><option value={x} key={x}>{x}%</option>)}</select></Field>
   </div>
   <div className={s.checks}>{([['includeHotel',ar?'السكن':'Stay'],['includeFood',ar?'الأكل':'Food'],['includeLocal',ar?'التنقل':'Transport'],['includeActivities',ar?'الأنشطة':'Experiences'],['includeEssentials',ar?'الضروريات':'Essentials']] as const).map(([key,text])=><button key={key} className={`${s.chip} ${form[key]!==false?s.chipOn:''}`} onClick={()=>set(key,!form[key])}>{form[key]!==false&&<Check size={13}/>} {text}</button>)}</div>
   <div className={s.searchRow}><span className={s.hint}>{ar?'الإضافات مثل الإنترنت والسائق والتأمين لا تدخل في ترتيب الأرخص؛ تضيفها بعد اختيار الرحلة.':'Internet, drivers, insurance and other add-ons are intentionally excluded from cheapest-trip ranking.'}</span><button className={s.primary} onClick={search} disabled={loading||mode==='destination'&&!form.destination}>{ar?'جيب أوفر الرحلات':'Find cheapest trips'}</button></div>{error&&<div className={s.error}>{error}</div>}
  </section>
  <section id="results" className={`${s.shell} ${s.results}`}>
   <div className={s.resultHead}><div><div className={s.eyebrow}>{ar?'النتائج':'RESULTS'}</div><h2>{searched?(within?ar?`${within} خيار داخل الميزانية`:`${within} options within budget`:ar?'أوفر الخيارات الموجودة':'Cheapest options found'):(ar?'نتائج رحلتك':'Your trip results')}</h2>{searched&&<p>{meta.datesScanned||0} {ar?'تاريخ تم فحصه · النتائج مرتبة حسب التكلفة الأساسية':'dates scanned · ranked by core trip cost'}</p>}</div>{searched&&<select className={s.sort} value={sortMode} onChange={e=>setSortMode(e.target.value as SortMode)}><option value="cheapest">{ar?'الأرخص إجمالًا':'Cheapest total'}</option><option value="remaining">{ar?'أكثر ميزانية متبقية':'Most budget left'}</option><option value="best">{ar?'أفضل تطابق':'Best match'}</option></select>}</div>
   {!searched?<div className={s.empty}>{ar?'حدد ميزانيتك وابحث، وبعدها اختر أي رحلة وكمّلها بالإضافات اللي تحتاجها.':'Set your trip details, search, then choose any result and customize it with add-ons.'}</div>:<div className={s.cards}>{sorted.map((trip,i)=>{const key=`${placeKey(trip)}-${trip.departure}`;const open=details===key;return <article className={`${s.card} ${i===0?s.cardBest:''}`} key={key}>{i===0&&<span className={s.badge}>{ar?'أوفر خيار':'CHEAPEST FOUND'}</span>}<div className={s.route}><strong>{label(trip.city,lang)}</strong><small>{label(trip.country,lang)} · {trip.carrier} · {trip.stops===0?(ar?'مباشر':'Direct'):`${trip.stops} ${ar?'توقف':'stop'}`}</small></div><div className={s.dates}><span>{dateLabel(trip.departure,lang)}</span>{trip.returnDate&&<span>→ {dateLabel(trip.returnDate,lang)}</span>}<span>· {trip.travelers} {ar?'مسافر':'traveler(s)'}</span><span>· {trip.nights} {ar?'ليلة':'night(s)'}</span></div><div className={s.costGrid}><Cost label={ar?'الطيران':'Flights'} amount={moneyNow(trip.costs.flight)}/><Cost label={ar?'السكن':'Stay'} amount={moneyNow(trip.costs.hotel)}/><Cost label={ar?'الأكل':'Food'} amount={moneyNow(trip.costs.food)}/><Cost label={ar?'التنقل':'Transport'} amount={moneyNow(trip.costs.local)}/><Cost label={ar?'الأنشطة':'Activities'} amount={moneyNow(trip.costs.activities)}/><Cost label={ar?'الضروريات':'Essentials'} amount={moneyNow(trip.costs.essentials)}/></div><div className={s.totalBox}><div><small>{ar?'تكلفة الرحلة الأساسية':'CORE TRIP COST'}</small><strong>{moneyNow(trip.costs.total)}</strong></div><div className={trip.remaining>=0?s.remainingGood:s.remainingBad}><small>{trip.remaining>=0?(ar?'متبقي':'left'):(ar?'تجاوز':'over')}</small><strong>{moneyNow(Math.abs(trip.remaining))}</strong></div></div><div className={s.cardActions}><button className={s.cardButton} onClick={()=>setDetails(open?null:key)}>{open?(ar?'إخفاء الحسبة':'Hide calculation'):(ar?'كيف حسبناها؟':'How was this calculated?')}</button><button className={`${s.cardButton} ${s.primaryCard}`} onClick={()=>openTrip(trip)}>{ar?'اختر الرحلة وكمّلها':'Choose & customize'}</button></div>{open&&<div className={s.details}>{trip.costLines.map(line=><div className={s.line} key={line.key}><div><strong>{lineName(line.key,lang)} <span className={s.confidence}>{confidence(line.confidence,lang)}</span></strong><small>{ar?translateBasis(line):line.formula}<br/>{ar?translateNote(line):line.basis}</small></div><strong>{moneyNow(line.amount)}</strong></div>)}</div>}</article>})}</div>}
  </section>
  {selectedTrip&&<div className={s.overlay} onMouseDown={e=>{if(e.target===e.currentTarget)setSelectedTrip(null)}}><section className={s.sheet}><div className={s.sheetHead}><div><div className={s.eyebrow}>{ar?'كمّلي رحلتك':'COMPLETE YOUR TRIP'}</div><h2>{label(selectedTrip.city,lang)} · {moneyNow(selectedTrip.costs.total)}</h2><p>{ar?'الإضافات منفصلة عن ترتيب أوفر رحلة. اختر فقط اللي تحتاجه.':'Add-ons stay separate from cheapest-trip ranking. Choose only what you need.'}</p></div><button className={s.close} onClick={()=>setSelectedTrip(null)}>×</button></div><div className={s.selectedTrip}><div><span>{ar?'الرحلة المختارة':'Selected trip'}</span><strong>{label(selectedTrip.city,lang)}, {label(selectedTrip.country,lang)}</strong></div><div><span>{ar?'المدة':'Duration'}</span><strong>{selectedTrip.days} {ar?'أيام':'days'} / {selectedTrip.nights} {ar?'ليالي':'nights'}</strong></div><div><span>{ar?'المسافرون':'Travelers'}</span><strong>{selectedTrip.adultsCount} {ar?'بالغ':'adult'} + {selectedTrip.childrenCount} {ar?'طفل':'child'}</strong></div><div><span>{ar?'الميزانية':'Budget'}</span><strong>{moneyNow(budgetSar)}</strong></div></div>
   <div className={s.sectionTitle}><div><h3>{ar?'الإنترنت والاتصال':'Internet & connectivity'}</h3><p>{ar?'اختر نوع واحد فقط؛ كلها تقديرات تخطيطية وليست حجوزات.':'Choose one type only; these are planning estimates, not bookings.'}</p></div></div><div className={s.addons}>{addons.filter(a=>a.group==='internet').map(a=><AddonCard key={a.id} addon={a} trip={selectedTrip} selected={selectedAddons.includes(a.id)} lang={lang} moneyNow={moneyNow} onClick={()=>toggleAddon(a)}/>)}</div>
   <div className={s.sectionTitle}><div><h3>{ar?'خدمات إضافية':'Trip add-ons'}</h3><p>{ar?'الأمتعة، التأمين، النقل الخاص، السائق، المرشد وتأجير السيارة.':'Baggage, insurance, private transfer, driver, guide and rental car.'}</p></div></div><div className={s.addons}>{addons.filter(a=>!a.group).map(a=><AddonCard key={a.id} addon={a} trip={selectedTrip} selected={selectedAddons.includes(a.id)} lang={lang} moneyNow={moneyNow} onClick={()=>toggleAddon(a)}/>)}</div>
   <div className={s.summary}><div className={s.summaryPanel}><h3>{ar?'الإضافات المختارة':'Selected add-ons'}</h3>{selectedAddonRows.length?selectedAddonRows.map(a=><div className={s.summaryRow} key={a.id}><span>{a.icon} {a.name[lang]}</span><strong>{moneyNow(a.amount)}</strong></div>):<p className={s.note}>{ar?'ما اخترت أي إضافة حتى الآن.':'No add-ons selected yet.'}</p>}<div className={s.summaryRow}><span>{ar?'مجموع الإضافات':'Add-ons total'}</span><strong>{moneyNow(addonTotal)}</strong></div></div><div className={s.summaryPanel}><div className={s.summaryRow}><span>{ar?'تكلفة الرحلة الأساسية':'Base trip'}</span><strong>{moneyNow(selectedTrip.costs.total)}</strong></div><div className={s.summaryRow}><span>{ar?'الإضافات':'Add-ons'}</span><strong>+ {moneyNow(addonTotal)}</strong></div><div className={`${s.summaryRow} ${s.final}`}><span>{ar?'الإجمالي النهائي':'FINAL TOTAL'}</span><strong>{moneyNow(finalTotal)}</strong></div><div className={s.summaryRow}><span>{ar?`احتياطي طوارئ مقترح ${selectedTrip.emergencyPct}%`:`Suggested ${selectedTrip.emergencyPct}% reserve`}</span><strong>{moneyNow(reserve)}</strong></div><div className={s.summaryRow}><span>{ar?'الميزانية الآمنة المقترحة':'Recommended safe budget'}</span><strong>{moneyNow(safeFinal)}</strong></div><div className={s.budgetMeter}><div className={`${s.budgetFill} ${finalTotal>budgetSar?s.budgetOver:''}`} style={{width:`${Math.min(100,finalTotal/Math.max(1,budgetSar)*100)}%`}}/></div><div className={s.summaryRow}><span>{finalRemaining>=0?(ar?'المتبقي من ميزانيتك':'Budget remaining'):(ar?'تجاوزت ميزانيتك':'Over budget')}</span><strong className={finalRemaining>=0?s.remainingGood:s.remainingBad}>{moneyNow(Math.abs(finalRemaining))}</strong></div><p className={s.note}>{ar?`بعد الاحتياطي المقترح: ${safeRemaining>=0?'يبقى':'ينقصك'} ${moneyNow(Math.abs(safeRemaining))}. أسعار الإضافات هنا تقديرات تخطيطية منفصلة ولا تغيّر ترتيب الرحلات الأصلي.`:`After the suggested reserve: ${safeRemaining>=0?'you keep':'you need'} ${moneyNow(Math.abs(safeRemaining))}. Add-on prices are separate planning estimates and never change the original cheapest-trip ranking.`}</p></div></div>
  </section></div>}
 </main>
}

function Field({title,children}:{title:string;children:React.ReactNode}){return <label className={s.field}><span>{title}</span>{children}</label>}
function Cost({label,amount}:{label:string;amount:string}){return <div className={s.costItem}><span>{label}</span><strong>{amount}</strong></div>}
function AddonCard({addon,trip,selected,lang,moneyNow,onClick}:{addon:Addon;trip:TripResult;selected:boolean;lang:Lang;moneyNow:(v:number)=>string;onClick:()=>void}){return <button className={`${s.addon} ${selected?s.addonOn:''}`} onClick={onClick}><span className={s.addonIcon}>{addon.icon}</span><span><strong>{selected?'✓ ':''}{addon.name[lang]}</strong><small>{addon.description[lang]}</small><small>{addon.basis[lang]}</small></span><span className={s.addonPrice}><strong>{moneyNow(addon.price(trip))}</strong><small>{lang==='ar'?'للرحلة':'trip estimate'}</small></span></button>}
function translateBasis(line:CostLine){const map:Record<CostLine['key'],string>={flight:'السعر حسب خط الرحلة وعدد المسافرين ونوع الذهاب/العودة.',hotel:'عدد الليالي × عدد الغرف × السعر المرجعي لليلة.',food:'عدد الأيام × البالغين + الأطفال بنسبة مخفضة.',local:'عدد الأيام × معامل تنقل المجموعة.',activities:'عدد الأيام × مخصص الأنشطة للمسافرين.',essentials:'عدد الأيام × مخصص الضروريات اليومية.',emergency:'نسبة الاحتياطي × تكلفة الرحلة الأساسية.'};return map[line.key]}
function translateNote(line:CostLine){const map:Record<CostLine['key'],string>={flight:line.confidence==='live'?'سعر مباشر من مزود الطيران المتصل.':'سعر مرجعي وليس حجزًا مباشرًا.',hotel:'سعر سكن مرجعي للوجهة وليس عرض فندق مباشر.',food:'ميزانية تقديرية للطعام وليست حجوزات مطاعم.',local:'مخصص تنقل عادي؛ السائق والسيارة الخاصة إضافات منفصلة.',activities:'ميزانية تقديرية للتجارب ولا تعني حجز نشاط محدد.',essentials:'مخصص للمياه والاحتياجات اليومية الصغيرة؛ الإنترنت والتأمين منفصلان.',emergency:'احتياطي أمان اختياري ولا يمثل خدمة تم شراؤها.'};return map[line.key]}